before_install: openssl aes-256-cbc -K $encrypted_cd813bb64b7a_key -iv $encrypted_cd813bb64b7a_iv -in ec2-teste.pem.enc -out ec2-teste.pem -d
script:
  - ssh -i "ec2-teste.pem" ec2-user@ec2-18-206-223-123.compute-1.amazonaws.com && echo yes
