version: "3.3"

networks:
  proxy:
    external: true

services:
  postgres:
    image: postgres:11
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  gateway:
    image: gesuvs/gateway
    environment:
      USER_SERVICE: ${USER_SERVICE}
      EVENTO_SERVICE: ${EVENTO_SERVICE}
    networks:
      - proxy
    depends_on:
      - postgres
    deploy:
      labels:
        - traefik.frontend.rule=PathPrefixStrip:/api
        - traefik.docker.network=proxy
        - traefik.port=7777
        - traefik.enable=true
  bora-user:
    image: gesuvs/user
    networks:
      - proxy
    depends_on:
      - postgres
      - gateway
    environment:
      HOST: ${HOST}
      USER_PORT: ${USER_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${USER_PORT}:${USER_PORT}
    command: >
      sh -c "yarn migrate && pm2-runtime dist/main.js"
  bora-evento:
    image: gesuvs/eventos
    networks:
      - proxy
    depends_on:
      - postgres
      - gateway
    environment:
      HOST: ${HOST}
      PORT: ${EVENTO_PORT}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    ports:
      - ${EVENTO_PORT}:${EVENTO_PORT}
    command: >
      sh -c "yarn migrate && pm2-runtime server.js"
