version: "3"
services:
  mongo:
    image: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=bora-upload
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "issue-upload:1:1,upload-response:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    build: .
    container_name: upload-service
    restart: always
    depends_on:
      - kafka
      - zookeeper
      - mongo
    environment:
      APP_PORT: ${APP_PORT}
      HOST: ${HOST}
      MONGO_URL: ${MONGO_URL}
      STORAGE_TYPE: ${STORAGE_TYPE}
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
      AWS_ACCESSS_KEY_ID: ${AWS_ACCESSS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    ports:
      - ${APP_PORT}:${APP_PORT}
    command: >
      sh -c "pm2-runtime src/index.js"
